version: '3'
services:
  backendpost: 
    build: ./back-end-post
    # volume option 
    volumes:
      - ./back-end-post:/usr/src/app 
    ports:
      - "5000:5000" 
  backendchat:
    build: ./back-end-chat
    ports: 
      - "3000:3000"
  frontend: 
    build: ./front-end
    ports: 
      - "8000:8000"
    volumes: 
      - ./front-end:/home/node/app    