CREATE TABLE post (
  id INT AUTO_INCREMENT NOT NULL,
  post TEXT NOT NULL,
  aggent VARCHAR(20) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE user (
  id INT AUTO_INCREMENT NOT NULL,
  aggent VARCHAR(20) NOT NULL,
  PRIMARY KEY(id)
);